"""
WARN: This is an autogenerated file. Do not edit this file manually.
"""
from typing import Dict

_JDK_TYPE_DATA = {
    # Java
    'Collection': 'java.util.Collection',
    'List': 'java.util.List',
    'ArrayList': 'java.util.ArrayList',
    'Set': 'java.util.Set',
    'HashSet': 'java.util.HashSet',
    'Map': 'java.util.Map',
    'HashMap': 'java.util.HashMap',
    'UUID': 'java.util.UUID',
    'Optional': 'java.util.Optional',
    'Stream': 'java.util.stream.Stream',
    'String': 'java.lang.String',
    'Double': 'java.lang.Double',
    'Float': 'java.lang.Float',
    'Integer': 'java.lang.Integer',
    'Short': 'java.lang.Short',
    'Long': 'java.lang.Long',
    'Boolean': 'java.lang.Boolean',
    'BigDecimal': 'java.math.BigDecimal',
    'BigInteger': 'java.math.BigInteger',
}

_SPRING_TYPE_DATA = {
    # Spring data
    'Page': 'org.springframework.data.domain.Page',
    'Pageable': 'org.springframework.data.domain.Pageable',
}


def get_type_data() -> Dict[str, str]:
    return {**_JDK_TYPE_DATA, **_SPRING_TYPE_DATA}
